<?php
ob_start();
session_start();
include './Applicant.php';
include './Application.php';
include './includes/helper_funcs.php';
if (!isset($_SESSION['id'])) {
    $url = './login.php';
    header("Location:" . $url);
}
// generate applicant information
$demographicInformation = new Applicant();
$registrationInformation = new Applicant();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./css/styles.css">
    <!-- <script src="script.js" defer></script> -->
    <title>Form</title>
</head>

<body>
    <div class="header-container">
        <div></div>
        <div></div>
        <div>
            <nav>
                <ul class="nav-container">
                    <div class="links">
                        <li><a href="index.php">Home</a></li>
                    </div>
                    <div>
                        <li class="links"><a href="courses.php">Courses</a></li>
                    </div>
                    <div>
                        <li class="links"><a href="logout.php">Logout</a></li>
                    </div>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        <div>
            <nav>
                <ul>
                    <li><a href="personal.php">Personal Information</a></li>
                    <li><a href="demographics.php">Demographic Information</a></li>
                    <li><a href="academics.php">Academic Information</a></li>
                    <li><a href="course.php<?php echo (isset($_GET['courseId']) ? '?courseId=' . $_GET['courseId'] : '') ?>">Select Course</a></li>
                    <li><a href="demographics.php">Parent/Guardian Information</a></li>
                    <li><a href="upload.php">Upload Documents</a></li>
                </ul>
            </nav>
        </div>
        <main>
            <h1>Application</h1>
            <h2>Demographic Information</h2>
            <div>
                <?php
                $record = $registrationInformation->selectApplicantByPhoneNumber($_SESSION['id'])[0];
                $id = $record['id'];

                $demographicInformation = new Application("demographic_information", null, $applicantId = $id, null, null, null);
                if ($demographicInformation->findInformationByApplicantId()) {
                    $row = $demographicInformation->findInformationByApplicantId()[0];
                }
                ?>
                <form action="" method="post" id="form">
                    <input type="hidden" name="applicant_id" value="<?php echo $id; ?>">
                    <div>
                        <label for="county">County</label>
                        <?php
                        $application = new Application("counties", null, null, "county", null, null);
                        $counties = $application->findAll();
                        ?>
                        <select name="county_id" id="county">
                            <!-- <option value="">--select your county--</option> -->
                            <option value="<?php echo (isset($row['county_id']) ? $row['county_id'] : "--select your county--"); ?>">
                                <?php echo (isset($row['county_id']) ? $application->findColumnById($row['county_id']) : "--select your county--"); ?>
                            </option>
                            <?php foreach ($counties as $county) { ?>
                                <option value="<?php echo $county['id']; ?>"><?php echo $county['county']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div>
                        <?php
                        $application = new Application("sub_counties", null, null, "sub_county", null, null);
                        // $sub_counties = $application->findAll();
                        ?>
                        <label for="sub_county">Sub County</label>
                        <select name="sub_county_id" id="sub_county">
                            <!-- options to be generated by ajax -->
                            <option value="<?php echo (isset($row['sub_county_id']) ? $row['sub_county_id'] : ''); ?>"><?php echo (isset($row['sub_county_id']) ? $application->findColumnById($row['sub_county_id']) : '--select your sub county--'); ?></option>
                        </select>
                    </div>
                    <div>
                        <label for="location">Location</label>
                        <input type="text" name="location" id="location" value="<?php echo (isset($row['location']) ? $row['location'] : '--provide your location--'); ?>" required>
                    </div>
                    <div>
                        <label for="sub_location">Sub-Location</label>
                        <input type="text" name="sub_location" id="sub_location" value="<?php echo (isset($row['sub_location']) ? $row['sub_location'] : '--provide your sub location--'); ?>" required>
                    </div>
                    <div>
                        <label for="village">Village</label>
                        <input type="text" name="village" id="village" value="<?php echo (isset($row['village']) ? $row['village'] : '--provide your village--'); ?>" required>
                    </div>
                    <div>

                    </div>
                    <div>
                        <input type="submit" name="submit" value="submit" id="submit">
                    </div>
                </form>
                <p id="message"></p>
                <?php
                if (isset($_POST["submit"])) {
                    $columns = "applicant_id, county_id, sub_county_id, location, sub_location, village";
                    $parameters = ":applicant_id, :county_id, :sub_county_id, :location, :sub_location, :village";
                    $updateString = "applicant_id = :applicant_id, county_id = :county_id, sub_county_id = :sub_county_id, location = :location, sub_location = :sub_location, village = :village";
                    $application = new Application("demographic_information", $_POST, $id, $columns, $parameters, $updateString);
                    if ($application->saveInformation()) {
                        echo "Saved Successifully";
                        refresh($_SERVER['PHP_SELF'], 3);
                    } else {
                        echo "Saving failure/no changes made";
                    }
                }
                ?>
            </div>
        </main>
        <div></div>
    </div>
    <script>
        document.getElementById("county").addEventListener("change", (event) => {
            var selectedCounty = document.getElementById("county");
            var url = "./get_sub_counties.php?county_id=" + encodeURIComponent(selectedCounty.value);
            fetch(url).then((response) => {
                if (!response.ok) {
                    console.log("response not okay");
                }
                return response.json();
            }).then((data) => {
                // get the select field
                var subCounty = document.getElementById("sub_county");
                subCounty.innerHTML = "";
                data.forEach((element) => {
                    var option = document.createElement("option");
                    // console.log(element.id, element.county_id, element.sub_county_id, element.sub_county);
                    option.value = element['id'];
                    option.textContent = element['sub_county']
                    subCounty.append(option)
                });
                var otherOption = document.createElement("option");
                otherOption.value = "other";
                otherOption.textContent = "Other";
                subCounty.append(otherOption);
            }).catch((error) => {
                console.error("There was a problem with the fetch operation", error);
            })
        });

        // check if other is selected
        document.getElementById("sub_county").addEventListener("change", (event) => {
            var subCounty = document.getElementById("sub_county");
            if (subCounty.value == "other") { // check if other is selected
                // create a div
                // nest an input in that field
                console.log("other has been selected");
            }
        });
    </script>
</body>

</html>
<?php ob_end_flush(); ?>