<?php
ob_start();
session_start();
include './Applicant.php';
include './Application.php';
include './includes/helper_funcs.php';
if (!isset($_SESSION['id'])) {
    $url = './login.php';
    header("Location:" . $url);
}
// generate applicant information
$demographicInformation = new Applicant();
$registrationInformation = new Applicant();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./css/styles.css">
    <script src="./js/demographic.js" defer></script>
    <title>Form</title>
</head>

<body>
    <div class="header-container">
        <div></div>
        <div></div>
        <div>
            <nav>
                <ul class="nav-container">
                    <div class="links">
                        <li><a href="index.php">Home</a></li>
                    </div>
                    <div>
                        <li class="links"><a href="courses.php">Courses</a></li>
                    </div>
                    <div>
                        <li class="links"><a href="logout.php">Logout</a></li>
                    </div>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        <div>
            <?php include './includes/side_navigation.php'; ?>
        </div>
        <main>
            <h1>Application</h1>
            <h2>Demographic Information</h2>
            <div style="background-color: wheat; padding: 10px; border: 1px solid grey; border-radius: 5px;">
                <?php
                $record = $registrationInformation->selectApplicantByPhoneNumber($_SESSION['id'])[0];
                $id = $record['id'];

                $demographicInformation = new Application("demographic_information", null, $applicantId = $id, null, null, null);
                if ($demographicInformation->findInformationByApplicantId()) {
                    $row = $demographicInformation->findInformationByApplicantId()[0];
                }
                ?>
                <form action="" method="post" id="form">
                    <input type="hidden" name="applicant_id" value="<?php echo $id; ?>">
                    <div>
                        <label for="county">County</label>
                        <?php
                        $application = new Application("counties", null, null, "county", null, null);
                        $counties = $application->findAll();
                        ?>
                        <select name="county_id" id="county">
                            <!-- <option value="">--select your county--</option> -->
                            <option value="<?php echo (isset($row['county_id']) ? $row['county_id'] : "--select your county--"); ?>">
                                <?php echo (isset($row['county_id']) ? $application->findColumnById($row['county_id']) : "--select your county--"); ?>
                            </option>
                            <?php foreach ($counties as $county) { ?>
                                <option value="<?php echo $county['id']; ?>"><?php echo $county['county']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div>
                        <?php
                        $application = new Application("sub_counties", null, null, "sub_county", null, null);
                        ?>
                        <label for="sub_county">Sub County</label>
                        <select name="sub_county_id" id="sub_county">
                            <!-- options to be generated by ajax -->
                            <option value="<?php echo (isset($row['sub_county_id']) ? $row['sub_county_id'] : ''); ?>"><?php echo (isset($row['sub_county_id']) ? $application->findColumnById($row['sub_county_id']) : '--select your sub county--'); ?></option>
                            <?php
                            $application = new Application('sub_counties', null, null, "county_id", null, null);
                            $subCounties = $application->findAllById($row['county_id']);
                            ?>
                            <?php foreach ($subCounties as $subCounty) { ?>
                                <option value="<?php echo $subCounty['id']; ?>"><?php echo $subCounty['sub_county']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div id="otherSubCounty" style="display: none;">
                        <label for="other_sub_county">Other Sub County(specify)</label>
                        <input type="text" name="other_sub_county">
                    </div>
                    <div>
                        <label for="location">Location</label>
                        <input type="text" name="location" id="location" value="<?php echo (isset($row['location']) ? $row['location'] : ''); ?>" placeholder="--provide your location--" required>
                    </div>
                    <div>
                        <label for="sub_location">Sub-Location</label>
                        <input type="text" name="sub_location" id="sub_location" value="<?php echo (isset($row['sub_location']) ? $row['sub_location'] : ''); ?>" placeholder="--provide your sub location--" required>
                    </div>
                    <div>
                        <label for="village">Village</label>
                        <input type="text" name="village" id="village" value="<?php echo (isset($row['village']) ? $row['village'] : ''); ?>" placeholder="--provide your village--" required>
                    </div>
                    <div>

                    </div>
                    <div>
                        <input type="submit" name="submit" value="save" id="submit">
                    </div>
                </form>
                <p id="message"></p>
                <?php
                if (isset($_POST["submit"]) && $_POST["sub_county_id"] !== "other") {
                    $columns = "applicant_id, county_id, sub_county_id, location, sub_location, village";
                    $parameters = ":applicant_id, :county_id, :sub_county_id, :location, :sub_location, :village";
                    $updateString = "applicant_id = :applicant_id, county_id = :county_id, sub_county_id = :sub_county_id, location = :location, sub_location = :sub_location, village = :village";
                    $application = new Application("demographic_information", $_POST, $id, $columns, $parameters, $updateString);
                    unset($application->post["other_sub_county"]); //unset this value
                    if ($application->saveInformation()) {
                        echo "Saved Successifully";
                        refresh($_SERVER['PHP_SELF'], 3);
                    } else {
                        echo "Saving failure/no changes made";
                    }

                    if (isset($_POST["submit"]) && $_POST["sub_county_id"] == "other") {
                        $columns = "applicant_id, county_id, sub_county_id, location, sub_location, village";
                        $parameters = ":applicant_id, :county_id, :sub_county_id, :other_sub_county, :location, :sub_location, :village";
                        $updateString = "applicant_id = :applicant_id, county_id = :county_id, sub_county_id = :sub_county_id, location = :location, sub_location = :sub_location, village = :village";
                        $application = new Application("demographic_information", $_POST, $id, $columns, $parameters, $updateString);
                        $insertId = $application->insertNewSubCounty();
                        if ($insertId > 0) {
                            $application->post['sub_county_id'] = $insertId;
                            if ($application->saveInformation()) {
                                echo "Saved Successifully";
                                refresh($_SERVER['PHP_SELF'], 3);
                            } else {
                                echo "Saving failure/no changes made";
                            }
                        }
                    }
                }
                ?>

                <?php
                $counties = new Application("counties", null, null, "county", null, null);
                $subCounties = new Application("sub_counties", null, null, "sub_county", null, null);
                if (isset($row)) { ?>
                    <h3>Saved Demographic Information</h3>
                    <table style="margin: 0;">
                        <tr>
                            <td>County</td>
                            <td><?php echo $counties->findColumnById($row['county_id']); ?></td>
                        </tr>
                        <tr>
                            <td>Sub County</td>
                            <td><?php echo $subCounties->findColumnById($row['sub_county_id']); ?></td>
                        </tr>
                        <tr>
                            <td>Location</td>
                            <td><?php echo $row['location']; ?></td>
                        </tr>
                        <tr>
                            <td>Sub Location</td>
                            <td><?php echo $row['sub_location']; ?></td>
                        </tr>
                        <tr>
                            <td>Village</td>
                            <td><?php echo $row['village']; ?></td>
                        </tr>
                    </table>
                <?php } ?>
            </div>
        </main>
        <div></div>
    </div>
</body>

</html>
<?php ob_end_flush(); ?>